# tensorflow 함수 테스트

tenserflow 예제에 나오는 함수를 분석해 보자

In [1]:
import tensorflow as tf
import numpy as np

sess=tf.Session()

In [2]:
xy = np.loadtxt('data-03-diabetes.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

- 파이선 함수는 인자명을 붙여주면 인자 순서에 상관없지 지정 가능하다.

In [3]:
X = tf.placeholder(tf.float32, shape=[None, 8])
Y = tf.placeholder(shape=[None, 1], dtype=tf.float32)

In [4]:
W = tf.Variable(tf.random_normal([8, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

- tf.random_normal 값의 형태를 확인해 보자

In [5]:
print(sess.run(tf.random_normal([8, 1])))

[[-1.30887687]
 [ 0.5701077 ]
 [-1.46596241]
 [ 0.43508625]
 [ 0.76553822]
 [ 0.57737488]
 [ 1.63493764]
 [ 2.16444492]]


In [6]:
print(sess.run(tf.random_normal([3, 2, 3])))

[[[ 0.30827361  0.27122012 -0.89042979]
  [ 0.94778174 -1.0010376   0.10045316]]

 [[-0.93272072  1.2163415  -1.42884195]
  [ 0.56576139 -1.74485254  0.04141613]]

 [[ 1.02781272  0.4957926  -0.68778503]
  [ 0.02775995  0.10684519 -0.44261852]]]


- 비교연산자를 사용하면 각 요소에 true, false 값이 할당된다.

In [7]:
y_data5 = y_data[:5]
print(y_data5)

[[ 0.]
 [ 1.]
 [ 0.]
 [ 1.]
 [ 0.]]


In [8]:
print(y_data5 > 0.5)

[[False]
 [ True]
 [False]
 [ True]
 [False]]


- tf.equal 함수도 true, false 값이 할당된다.

In [9]:
y_data6_10 = y_data[5:10]
print(y_data6_10)
print(sess.run(tf.equal(y_data5, y_data6_10)))

[[ 1.]
 [ 0.]
 [ 1.]
 [ 0.]
 [ 0.]]
[[False]
 [False]
 [False]
 [False]
 [ True]]


- tf.cast는 형변환한다

In [10]:
print(sess.run(tf.cast(tf.equal(y_data5, y_data6_10), dtype=tf.float32)))

[[ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 1.]]


- tf.one_hot 함수

In [13]:
xy2 = np.loadtxt('data-04-zoo.csv', delimiter=',', dtype=np.float32)
y_data2 = xy2[:5, [-1]]
nb_classes = 7
print(y_data2)

[[ 0.]
 [ 0.]
 [ 3.]
 [ 0.]
 [ 0.]]


In [17]:
Y_one_hot = tf.one_hot(y_data2, nb_classes)
print(sess.run(Y_one_hot), "\n", Y_one_hot.shape)

[[[ 1.  0.  0.  0.  0.  0.  0.]]

 [[ 1.  0.  0.  0.  0.  0.  0.]]

 [[ 0.  0.  0.  1.  0.  0.  0.]]

 [[ 1.  0.  0.  0.  0.  0.  0.]]

 [[ 1.  0.  0.  0.  0.  0.  0.]]] 
 (5, 1, 7)


- tf.reshape 함수

https://www.tensorflow.org/api_docs/python/tf/reshape

In [18]:
Y_one_hot = tf.reshape(Y_one_hot, [-1, nb_classes])
print(sess.run(Y_one_hot), "\n", Y_one_hot.shape)

[[ 1.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.]] 
 (5, 7)
